import { createRequire } from 'node:module';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(path.join(root, 'web/package.json'));
const { chromium, expect } = require('@playwright/test');
const output = path.join(root, 'artifacts/map-review');
await mkdir(output, { recursive: true });
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
const base = 'http://127.0.0.1:8000';
try {
  await page.request.post(`${base}/api/v1/settings`, { data: { mode: 'simulation', impactScope: 'local_segment' } });
  await page.request.post(`${base}/api/v1/scenarios/reset`, { data: {} });
  await page.goto(base);
  await expect(page.getByTestId('map')).toHaveAttribute('data-basemap', 'osm');
  await expect(page.getByRole('button', { name: 'Run scenario' })).toBeEnabled();
  const labels = await page.locator('[data-map-label]').allTextContents();
  const layers = await page.locator('[data-map-kind]').evaluateAll(elements => elements.reduce((counts, e) => { const k = e.getAttribute('data-map-kind'); counts[k] = (counts[k] ?? 0) + 1; return counts; }, {}));
  await page.screenshot({ path: path.join(output, 'desktop.png'), animations: 'disabled' });
  for (let i = 0; i < 3; i++) await page.getByRole('button', { name: 'Zoom in', exact: true }).click();
  await page.screenshot({ path: path.join(output, 'street-detail.png'), animations: 'disabled' });
  await page.getByRole('button', { name: 'View full route', exact: true }).click();
  await page.screenshot({ path: path.join(output, 'full-route.png'), animations: 'disabled' });
  await page.getByRole('button', { name: 'Return to Stop 116', exact: true }).click();
  await page.request.post(`${base}/api/v1/scenarios/manual`, { data: { level: 60 } });
  await expect(page.getByTestId('hazard-state')).toHaveText('Warning', { timeout: 15000 });
  await page.screenshot({ path: path.join(output, 'warning.png'), animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.locator('.offline-map').getAttribute('viewBox')).toMatch(/^0 0 390 /);
  await page.screenshot({ path: path.join(output, 'mobile.png'), animations: 'disabled' });
  const mobileLabels = await page.locator('[data-map-label]').allTextContents();
  const report = { capturedAt: new Date().toISOString(), layers, labels, mobileLabels, browserErrors: errors, screenshots: ['desktop.png', 'street-detail.png', 'full-route.png', 'warning.png', 'mobile.png'] };
  await writeFile(path.join(output, 'report.json'), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
} finally { await page.request.post(`${base}/api/v1/scenarios/reset`, { data: {} }).catch(() => undefined); await browser.close(); }
